# Generated by Django 5.2.7 on 2025-10-29 20:00

from django.db import migrations


def seed_replacement_parts(apps, schema_editor):
    """Seeds the database with initial replacement parts."""
    replacement_part = apps.get_model('api', 'ReplacementPart')
    initial_data = [
        {'name': 'Oil Filter', 'sku': 'OF-1022', 'quantity': 150},
        {'name': 'Air Filter', 'sku': 'AF-3045', 'quantity': 200},
        {'name': 'Spark Plug', 'sku': 'SP-BKR6E', 'quantity': 500},
        {'name': 'Brake Pad Set', 'sku': 'BP-S-456', 'quantity': 75},
    ]

    for data in initial_data:
        # Check if a part with the same SKU already exists to avoid duplicates
        if not replacement_part.objects.filter(sku=data['sku']).exists():
            replacement_part.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_replacement_parts),
    ]
