name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.14"] # You can add more versions like "3.11", "3.10"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    - name: Run Django Tests
      # The SECRET_KEY can be a dummy value for testing purposes
      # The database will use the default SQLite in-memory backend for tests
      env:
        SECRET_KEY: 'dummy-secret-key-for-testing'
        DJANGO_SETTINGS_MODULE: 'DjangoSample.settings'
      run: |
        poetry run python manage.py test
